-- Run this in the Supabase SQL Editor to create the sensor_data table

CREATE TABLE sensor_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc', NOW()) NOT NULL,
    load NUMERIC NOT NULL,
    vibration NUMERIC NOT NULL,
    temperature NUMERIC NOT NULL,
    humidity NUMERIC NOT NULL,
    pressure NUMERIC NOT NULL,
    accelerometer NUMERIC NOT NULL,
    gyroscope NUMERIC NOT NULL,
    rain_sensor INTEGER NOT NULL,
    strain TEXT NOT NULL,
    rain TEXT NOT NULL,
    health INTEGER NOT NULL,
    risk TEXT NOT NULL
);

-- Optional: Create an index on created_at for faster time-series queries
CREATE INDEX idx_sensor_data_created_at ON sensor_data(created_at DESC);
